name: WordFlake
main: plugin.WordFlake.WordFlake
version: 1.0.7
commands:
  wordr:
    description: Reload.
  wordadd:
    description: Add word.
permissions:
  wordflake.perms:
    description: Complete permission over plugin.
